name: Lint and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v7

      - uses: actions/setup-python@v6
        with:
          python-version: '3.11.16'
          cache: 'pip'

      - name: Lint
        run: make lint

      - name: Check format
        run: make check-format

      - name: Check requirements
        run: make check-requirements

      - name: Test
        run: make test
